name: Matrixe Project
on: push

jobs:
  deploy:
    continue-on-error: true
    strategy:
      matrix:
        node-versions: [12,14,16]
        os: [ubuntu-latest,windows-latest]
        include:
          - node-versions: 18
            os: ubuntu-latest
        exclude:
          - node-versions: 12
            os: windows-latest

    runs-on: ${{ matrix.os}}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-versions }}
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo Deploying now...